### ISSUE TITLE
Script not POSIX on OpenBSD

### ISSUE THREAD

**Issue by MitchWeaver** [lwilletts/mpvc#37]
Not currently working with the #!/bin/sh shebang that comes default on OpenBSD, (which has /bin/sh linked to ksh)

proof:
![Image](https://0x0.st/sKZa.png)

Changing the shebang to /bin/bash solves all problems -- works flawlessly.

Request: make POSIX to remove bash dependency

**Comment by heckendorfc** [comment]
Try the latest commit and let me know how it works for you.

**Comment by MitchWeaver** [comment]
Works great, thanks! :+1:

**Comment by heckendorfc** [comment]
Cool, thanks for reporting.

@lwilletts was there a specific platform you found that `type` didn't work on? `hash` can't be used to check for a program's existence on ksh since it doesn't return anything.

**Comment by lwilletts** [comment]
Was not aware of the difference on ksh. Recommend we go back to using `type` for everything.
