### ISSUE TITLE
Suggestion: make mpvc busybox compatible

### ISSUE THREAD

**Issue by MitchWeaver** [lwilletts/mpvc#38]
`nc`  - busybox's nc does not have the `-U` or `-N` flags

**Solution**: install `socat`

`grep` - busybox's grep does not have the `-G` flag

**Solution**: install `gnugrep`

Could there be a work around?

**Comment by lwilletts** [comment]
If you read the source code, I included both nc and socat in the programming with nc preferred as default as nc generally comes by default on most linux distros. Try modifying line #779 to see if you can get your version of nc to work when talking to the mpv socket, give me the flags you used if successful and I'll include a busybox check.

-G just specifies to use basic ragexp and is actually the default behavior of gnu grep, so I'm not sure why I included that flag in the first place. Try removing the -G flag from grep on line #737 and tell me if mpvc behaves correctly. If so, I'll remove the flag.

**Comment by heckendorfc** [comment]
It looks like I'm actually the one that added the -G, probably trying to avoid problems on some unseen platform that defaults to a different syntax. It seems to work fine without it on FreeBSD and I assume OpenBSD as well. I see no problem with removing the flag.

**Comment by lwilletts** [comment]
Go for it then, I have no issue with it.

**Comment by lwilletts** [comment]
Gonna presume that this is not an issue anymore seeing as @MitchWeaver never got back to us.
