### ISSUE TITLE
Add fuzzy string search through playlist titles to play closest match.

### ISSUE THREAD

**Issue by lwilletts** [lwilletts/mpvc#42]
Probably as part of --play.

**Comment by Tmplt** [comment]
Do you have a tool in mind for this? If not I can eventually resolve https://github.com/Tmplt/fuzzywuzzy/issues/6.

**Comment by lwilletts** [comment]
No I didn't at all! I think your tool looks interesting but I've always tried to design mpvc with the absolute minimum of tools to achieve tasks - I hadn't even looked at using a shell json phaser like jq. I think this issue might be best resolved by people using their own separate fuzzy finders like fzf and then pipe the input to mpvc add. I could do with figuring a basic solution out and then adding to the readme. Thanks for reminding me of this though!

**Comment by gmt4** [comment]
Currently, fuzzy string search is provided by fzf in [mpvc-fzf](https://github.com/lwilletts/mpvc/blob/master/extras/mpvc-fzf), and, is explained in https://gmt4.github.io/mpvc/logbook.html#logbook-20221227. So I think this can be closed as completed, thx.
