### ISSUE TITLE
Factoring and enqueuing https:// URLs (enhancement)

### ISSUE THREAD

**Issue by gmt4** [lwilletts/mpvc#46]
Hi there, 

Forked the code at https://github.com/gmt4/mpvc/commits/master,
For now it's been just a few minor things to get going, such as:
-  Factoring a bit the code
-  Minor changes for enqueuing https:// URL  with: `mpvc -a https://...`

Just to let you know in case there's something you find useful.

**Comment by gmt4** [comment]
Pull Request opened at https://github.com/lwilletts/mpvc/pull/48

**Comment by gmt4** [comment]
I synced mpvc with upstream and did a commit of the changes as a single commit:
https://github.com/gmt4/mpvc/commit/c4fa6a74ed6ab94578d727e780bbaedb461ed508

**Comment by gmt4** [comment]
I synced mpvc with upstream and did a commit of the changes as a single commit: 

https://github.com/gmt4/mpvc/commit/ec5e1ab1e596f2047a18b69f7cb71da488273cfa

**Comment by gmt4** [comment]
There's been  performance & new features improvements in  the https://github.com/gmt4/mpvc fork. Is there interest in merging these changes back?

**Comment by lwilletts** [comment]
Merged.
