### ISSUE TITLE
feature request: add next / insert

### ISSUE THREAD

**Issue by rybka123** [lwilletts/mpvc#47]
I'm not knowledgeable enough to implement this myself, but an "insert" or "addnext" function like in mpc would be useful. All it does is add a song after the currently playing song in the queue.

Otherwise, I really like this script.

**Comment by lwilletts** [comment]
Definitely doable for a single file easily. Will require a think for multiple arguments. If you're after a single song you can add it then use `mpvc play $` to get to it in the mean time, then shuffle again if wanted?

**Comment by rybka123** [comment]
That sounds good, mpvc play $ works but it would be ideal to be able to do this without changing your position in the queue. Like if the files are in specific order and you want to bring one to the front. I didn't think of doing this with multiple files at a time but that's a good idea.

I guess this could also work if there was a parameter for the number of the current file. So you could add a file and then move it to the number of the currently playing file plus one.

**Comment by lwilletts** [comment]
just realised I did actually code this functionality already duh.

use mpvc -A or --playnext / playnext followed by the file name for it to be inserted into the next position

however this will only work for a single file

**Comment by rybka123** [comment]
Damn I didn't realize this.
Thank you
