### ISSUE TITLE
New release (June 2022)

### ISSUE THREAD

**Issue by m040601** [lwilletts/mpvc#50]
Great project ! Love that it uses simple good old Unix tools and requires no complicated dependencies

I'm trying to test this on Archlinux. Unfortunately we currently only have a "mpvc-git" PKGBUILD recipee. It builds pulling  from github master. And worse, it is currently broken, https://aur.archlinux.org/packages/mpvc-git.

I would like to test this with a proper "mpvc" PKGBUILD. Not a "mpvc-git" PKGBUILD. The last release is from 2020. And I see a lot of activity recently since last year.

Could you please tag and release a new one ?
Thanks in advance

https://github.com/lwilletts/mpvc/issues/43

**Comment by lwilletts** [comment]
Now updated.
