### ISSUE TITLE
mpvc is not able anymore to add folders or YT videos to a playlist

### ISSUE THREAD

**Issue by crshrprt** [lwilletts/mpvc#52]
I've been a long time enjoyer of mpvc since 2017, with my personal little addition mentioned here: https://github.com/lwilletts/mpvc/issues/40#issuecomment-1275868452.

However, after many years of not updating mpvc I finally took the time to try the new commits.

Since commit https://github.com/lwilletts/mpvc/commit/7f3543c1c711d03a732c98287b1a19cf06f7a1fc mpvc seems to have lost the ability to add folders or YT videos to a playlist.

For example when adding a YT video with: 
`mpvc add ytvideourl` 

I get:
`/tmp/mpvsocket does not exist. Use mpv --input-ipc-server to start one. `

and if I manually create the socket with mpv:
`No files added to /tmp/mpvsocket`

It works only when I add files with absolute paths.

I use: 
Debian Sid
bash 5.2.0
mpv 0.34.1

**Comment by gmt4** [comment]
Check if https://github.com/gmt4/mpvc/commit/fccc03eb6db8d43e6b56201a9b256c1b7687dbbd solves the issue.
One of the reasons to fork at https://github.com/gmt4/mpvc/ was to be able to enqueue URLs, hope I haven't screwed it in the mean time.

**Comment by crshrprt** [comment]
Yes, your fork works with URLs. :)

**Comment by gmt4** [comment]
Pushed a new batch of changes, among them: a mpvc-tui, playlist manipulation a la: mpvc save | grep artist | mpvc load, and probably a bug or two. I'm keeping a log of the changes at https://gmt4.github.io/mpvc/ just in case anybody finds it addresses similar usage patterns.

**Comment by lwilletts** [comment]
Fork merged should solve this issue in main branch.
